/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisualLearningRouteImport } from './routes/_authenticated/visual-learning'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPapersRouteImport } from './routes/_authenticated/papers'
import { Route as AuthenticatedOfflineVideosRouteImport } from './routes/_authenticated/offline-videos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAiProvidersRouteImport } from './routes/_authenticated/ai-providers'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin-videos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedWatchContentIdRouteImport } from './routes/_authenticated/watch.$contentId'
import { Route as AuthenticatedTeacherCourseIdRouteImport } from './routes/_authenticated/teacher.$courseId'
import { Route as AuthenticatedLessonsLessonIdRouteImport } from './routes/_authenticated/lessons.$lessonId'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisualLearningRoute =
  AuthenticatedVisualLearningRouteImport.update({
    id: '/visual-learning',
    path: '/visual-learning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPapersRoute = AuthenticatedPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfflineVideosRoute =
  AuthenticatedOfflineVideosRouteImport.update({
    id: '/offline-videos',
    path: '/offline-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiProvidersRoute =
  AuthenticatedAiProvidersRouteImport.update({
    id: '/ai-providers',
    path: '/ai-providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/admin-videos',
    path: '/admin-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchContentIdRoute =
  AuthenticatedWatchContentIdRouteImport.update({
    id: '/watch/$contentId',
    path: '/watch/$contentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCourseIdRoute =
  AuthenticatedTeacherCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedLessonsLessonIdRoute =
  AuthenticatedLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-videos': typeof AuthenticatedAdminVideosRoute
  '/ai-providers': typeof AuthenticatedAiProvidersRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/offline-videos': typeof AuthenticatedOfflineVideosRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/visual-learning': typeof AuthenticatedVisualLearningRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/teacher/$courseId': typeof AuthenticatedTeacherCourseIdRoute
  '/watch/$contentId': typeof AuthenticatedWatchContentIdRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-videos': typeof AuthenticatedAdminVideosRoute
  '/ai-providers': typeof AuthenticatedAiProvidersRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/offline-videos': typeof AuthenticatedOfflineVideosRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/visual-learning': typeof AuthenticatedVisualLearningRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/teacher/$courseId': typeof AuthenticatedTeacherCourseIdRoute
  '/watch/$contentId': typeof AuthenticatedWatchContentIdRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/ai-providers': typeof AuthenticatedAiProvidersRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/offline-videos': typeof AuthenticatedOfflineVideosRoute
  '/_authenticated/papers': typeof AuthenticatedPapersRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/visual-learning': typeof AuthenticatedVisualLearningRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/_authenticated/teacher/$courseId': typeof AuthenticatedTeacherCourseIdRoute
  '/_authenticated/watch/$contentId': typeof AuthenticatedWatchContentIdRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-videos'
    | '/ai-providers'
    | '/assistant'
    | '/bookmarks'
    | '/dashboard'
    | '/offline-videos'
    | '/papers'
    | '/search'
    | '/settings'
    | '/teacher'
    | '/visual-learning'
    | '/courses/$courseId'
    | '/lessons/$lessonId'
    | '/teacher/$courseId'
    | '/watch/$contentId'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-videos'
    | '/ai-providers'
    | '/assistant'
    | '/bookmarks'
    | '/dashboard'
    | '/offline-videos'
    | '/papers'
    | '/search'
    | '/settings'
    | '/teacher'
    | '/visual-learning'
    | '/courses/$courseId'
    | '/lessons/$lessonId'
    | '/teacher/$courseId'
    | '/watch/$contentId'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin-videos'
    | '/_authenticated/ai-providers'
    | '/_authenticated/assistant'
    | '/_authenticated/bookmarks'
    | '/_authenticated/dashboard'
    | '/_authenticated/offline-videos'
    | '/_authenticated/papers'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/teacher'
    | '/_authenticated/visual-learning'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/lessons/$lessonId'
    | '/_authenticated/teacher/$courseId'
    | '/_authenticated/watch/$contentId'
    | '/_authenticated/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visual-learning': {
      id: '/_authenticated/visual-learning'
      path: '/visual-learning'
      fullPath: '/visual-learning'
      preLoaderRoute: typeof AuthenticatedVisualLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papers': {
      id: '/_authenticated/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AuthenticatedPapersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offline-videos': {
      id: '/_authenticated/offline-videos'
      path: '/offline-videos'
      fullPath: '/offline-videos'
      preLoaderRoute: typeof AuthenticatedOfflineVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-providers': {
      id: '/_authenticated/ai-providers'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof AuthenticatedAiProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-videos': {
      id: '/_authenticated/admin-videos'
      path: '/admin-videos'
      fullPath: '/admin-videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$contentId': {
      id: '/_authenticated/watch/$contentId'
      path: '/watch/$contentId'
      fullPath: '/watch/$contentId'
      preLoaderRoute: typeof AuthenticatedWatchContentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/$courseId': {
      id: '/_authenticated/teacher/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCourseIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/lessons/$lessonId': {
      id: '/_authenticated/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherCourseIdRoute: typeof AuthenticatedTeacherCourseIdRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherCourseIdRoute: AuthenticatedTeacherCourseIdRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAiProvidersRoute: typeof AuthenticatedAiProvidersRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOfflineVideosRoute: typeof AuthenticatedOfflineVideosRoute
  AuthenticatedPapersRoute: typeof AuthenticatedPapersRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
  AuthenticatedVisualLearningRoute: typeof AuthenticatedVisualLearningRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedLessonsLessonIdRoute: typeof AuthenticatedLessonsLessonIdRoute
  AuthenticatedWatchContentIdRoute: typeof AuthenticatedWatchContentIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAiProvidersRoute: AuthenticatedAiProvidersRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOfflineVideosRoute: AuthenticatedOfflineVideosRoute,
  AuthenticatedPapersRoute: AuthenticatedPapersRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
  AuthenticatedVisualLearningRoute: AuthenticatedVisualLearningRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedLessonsLessonIdRoute: AuthenticatedLessonsLessonIdRoute,
  AuthenticatedWatchContentIdRoute: AuthenticatedWatchContentIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
